### ISSUE TITLE
Support for local database 

### ISSUE THREAD

**Issue by ChristopherTotty** [NativeScript/cross-platform-modules#141]
It would be great if there were a module that interfaces with the native classes for SQLite database access.  This would allow a user to write JS once to interact with local data on any supported platform.

**Comment by ca-miro** [comment]
I'd love to see this too. We use it in one of our apps and would need it if we are to redo it in NativeScript

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#73

**Comment by Nathanaela** [comment]
Just a fyi; I just pushed "nativescript-sqlite" -- it only has the Android side done currently and it is a early alpha.   But it is available for playing with.  My repo is http://github.com/nathanaela/nativescript-sqlite     -- If there are any iPhone users out here; I wouldn't mind a tester to test out the iphone side of things when I complete it.
@enchev  - you closed both issues.
