### ISSUE TITLE
TextField text got striped

### ISSUE THREAD

**Issue by tjwudi** [NativeScript/cross-platform-modules#144]
I am using code from the **tasks example** in official docs. XML looks like this:

```xml
<TextField width="200" text="{{ task }}" hint="Enter a task" id="task" />
```

JavaScript
```javascript
exports.add = function() {
    console.log(pageData.get("task")); 
    tasks.push({ name: pageData.get("task") });
    pageData.set("task", "");
    viewModule.getViewById( page, "task" ).dismissSoftInput();
};
```

When I add an item named `My application`, I got the last `n` striped. `console.log` outputs `My applicatio`. Same issue happens to any other inputs. When I input Chinese, it actually strips more words, not just one.
![2 pic](https://cloud.githubusercontent.com/assets/5257816/6540062/4b658e1e-c4c5-11e4-91c2-b345ed17bd5c.jpg)

**Comment by hamorphis** [comment]
Can you take a look at this issue and confirm that your app is using the latest sources: https://github.com/NativeScript/cross-platform-modules/issues/129

**Comment by hamorphis** [comment]
You can pull the latest source code and update your project manually or you can wait for an official release.

**Comment by tjwudi** [comment]
@hamorphis Thanks for that. I will close this issue and watch  that issue.
