### ISSUE TITLE
Support for SignalR and NGINX Pushstream

### ISSUE THREAD

**Issue by kdubious** [NativeScript/cross-platform-modules#145]
It would be great to have access to "websocket" style notifications from tools like SignalR and Pushstream.

**Comment by hamorphis** [comment]
Can you provide an example technology or other JavaScript libraries that support these. Please, elaborate on what features and functionality you would expect from such a NativeScript module. Dummy sample code would also be very helpful. In other words, point us in the right direction.

**Comment by kdubious** [comment]
Hi. Pushstream is a small JS file provided by NGINX to work with their 2-way we socket based communication platform. SignalR is the Microsoft approach.

My suggestion would be to create modules to work with these 2 technologies.

Pushstream makes use of "window.", so it wont work out of the box.

We would like to write an app that controls a piece of hardware on the local network. An IoT device. This device uses an NGINX webserver. We need our NativeScript client app to be able to subscribe to the pushstream web socket to get real time updates from the server.

Perhaps Pushstream.js can be easily rewritten to do what we need, but I have not yet been able to remove the dependencies on "window."

Does NativeScript support "websockets"? Can you have a look at pushstream.js?

**Comment by kdubious** [comment]
Here are a few items from the pushstream.js file that would need to be addressed:

`window.WebSocket`
`window.JSON.parse()`
`window.XMLHttpRequest();`
`window.XDomainRequest();`
`window.setTimeout()`
`window.attachEvent()`
`window.addEventListener()`

Can these be converted for use in NativeScript?

**Comment by jopima** [comment]
Am also looking at the possibility of Using NativeScript with SignalR. There is a possibility of having this done with .net client apps (desktop) but around a non .net client and out of web context. am curious to know the hows.

**Comment by ligaz** [comment]
Here is Cordova plugin that implements the WebSockets API for Android. We can use it as a reference: https://github.com/knowledgecode/WebSocket-for-Android

**Comment by ligaz** [comment]
@kdubious Apart from mimicking the WebSocket API the [`pushstream.js`](https://github.com/wandenberg/nginx-push-stream-module/blob/master/misc/js/pushstream.js) is also using the `document` and some browser specific elements like `head` and `iframe` tags. This have to be abstracted in the `pushstream` code base in order to be able to run outside of the browser context.

**Comment by kdubious** [comment]
I can deal with re-writing Pushstream.js, if there is a means of accessing WebSockets. To be honest, I'm not far along the NativeScript learning curve, but I think a supported WebSocket client would get me started. Am I missing something obvious, ligaz?

**Comment by ligaz** [comment]
I can give you a pointer how I would have approached writing WebSocket support for NativeScript but you should be warn that this is not a walk in the part :warning: 

Here are the steps:
1. I would take the [Jetty code](https://github.com/knowledgecode/WebSocket-for-Android/tree/master/src/android/org/eclipse/jetty) that is used in the Cordova plugin and compile it as jar.
2. Having the jar I will use the `tns library add` to and it to a NativeScript project.
3. I will re-write the [Java code](https://github.com/knowledgecode/WebSocket-for-Android/tree/master/src/android/com/knowledgecode/cordova/websocket) in the Cordova plugin to JavaScript. I will constantly consult with [NativeScript Android runtime documentation](http://docs.nativescript.org/runtimes/android/overview).
4. I will adapt [the JavaScript part](https://github.com/knowledgecode/WebSocket-for-Android/blob/master/www/websocket.js) of the plugin so it does not use the Cordova bridge for communication but rather the JavaScript code I have previously written.
5. Test and debug until I make it work :sweat_smile:

Hope this helps get you started.

**Comment by broderix** [comment]
Hi, @ligaz, any updates? Thank you!

**Comment by ligaz** [comment]
Hey @broderix,

I was just giving a pointer how I would have approached the problem. If you are willing to jump on it I can help you along the way.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#72
