### ISSUE TITLE
Push Notification ???

### ISSUE THREAD

**Issue by sunel** [NativeScript/cross-platform-modules#153]
HI

I am wondering how push notification are handled and local notification too. and is there any documentation for this cross platform modules

**Comment by MathieuDoyon** [comment]
+1

**Comment by roja** [comment]
+1 this goes for all events which traditionally perform a callback within a native app. I.e. Geo fencing etc...

**Comment by tiagordc** [comment]
+1

**Comment by Igcorreia** [comment]
+1

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#71
