### ISSUE TITLE
Resolution-specific views

### ISSUE THREAD

**Issue by hshristov** [NativeScript/cross-platform-modules#154]
A way to specify resolution (density) specific XML files so user can have different views on different screens.

**Comment by vakrilov** [comment]
Here is a suggestion for implementation. The idea is to support different *qualifiers* inside the file name that will be respected when the file is loaded. Here is how the file should look like:

`<file-name>[.<qualifier>]*.<extension>`

It is somewhat similar to [multi screen support in android](http://developer.android.com/guide/practices/screens_support.html).

## Screen Size Qualifiers
All the values in screen size qualifiers are in density independent pixels(dp) – meaning it corresponds to the physical dimensions of the screen. The assumptions is that there are ~160 dp per inch. For example, according to android guidelines if the device’s smaller dimension is more than 600dp(~3.75 inches) it is probably tablet.
* `minWH<x>` - The smaller dimension should be at least x dp.
* `minW<x>` - Width should be at least x dp.
* `minH<x>` - Height should be at least x dp.

## Form Factor Qualifiers
* `tablet` - specifies the device is tablet. Note: in android this is similar to minWH600 qualifier as there is no sure way to check the type of the device. 
* `phone` - specifies the device is phone. 

These qualifiers are less specific than the screen size qualifiers and they have overlapping function. However, they seem easier to use. 

## Platform Qualifiers
* `android` – android platform
* `ios` – iOs platform
* `windows` – windows platform

We already have this functionality in place through the CLI prepare command. However, from native-script developer perspective – it is the same.

## Orientation Qualifiers
* `land` - orientation is in landscape mode
* `port` - orientation is in portrait mode

**Comment by valentinstoychev** [comment]
This proposal sounds good to me. I'm not sure if we need both per screen size qualifiers AND phone/table qualifiers. I would leave only the screen size qualifiers as a start.

We should keep the naming consistent with the resolution-based Image loading - https://github.com/NativeScript/cross-platform-modules/issues/156 

We will be able to mix qualifiers? Will it be possible to name a view - *mainPage.ios.land.xml* and be able also to have *mainPage.ios.port.xml*?

**Comment by PolCPP** [comment]
Sounds good but i'm not sure about the orientation qualifiers, wouldn't rotating the device trigger a view reload losing state?

**Comment by hkosev** [comment]
I'd rather like to be able to use media queries in CSS than creating a separate file for each screen size / orientation / form factor / etc. A completely separate view for each combination of these parameters sounds a bit too much IMO.

**Comment by sitefinitysteve** [comment]
@hkosev I disagree, I want different layouts entirely based on form factor...

Example: tablet layouts have the space to support a listview pane on the left and detail pane on the right.  Whereas on a phone I would prefer a simple list that loads a detail view.  I don't want to muck them all together in the same xml file and do some sort of bloaty hide\show media queries hack (we're not a browser anymore remember, I don't think they can just use them)

**Comment by jimulle** [comment]
I second @hkosev that CSS media queries would be my preferred method.

**Comment by hkosev** [comment]
@sitefinitysteve I agree, there are scenarios, like the one you've just described, where having different views is the way to go. So having form factor qualifiers and platform qualifiers could make sense.
But I think there are a lot of other scenarios like:
- I like to make something bigger on devices which have bigger screens
- I want to hide/show details on devices with smaller/bigger screens
- I want to hide/show something in portrait/landscape mode
- Etc.

And having a different view for each scenario sounds like a nightmare to me.
Every change you make to one view, you need to go and apply to all other views (could be a lot if we want to support many screen sizes).

**Comment by PolCPP** [comment]
@hkosev well you could always use a build script that concats view.css and viewtemp.1024.css into view.1024.css but yes, both things are neccesary, plus with mq you could manage rotation changes better than using a different file for direction

**Comment by sitefinitysteve** [comment]
Just to clarify my point, I wouldn't want a different file per rotation, just per device size.  Like my ipad layout would be similar enough regardless of rotation, however I would prefer if the app looked entirely different on an iphone so I would prefer another layout file instead of like needing the same bindable elements duplicated just hidden\shown based on space.

**Comment by vakrilov** [comment]
Looks to me one can achieve best results with combined(device-specific views + media queries) approach.
As @PolCPP pointed out orientation can be changed after the view is loaded you need a way to handle that. In Android you can either let the whole activity reload(the default behavior) or you can chose to handle orientation change yourself - both are tricky. However, if you are using the **minWH\<N\>** (equivalent to **sw\<N\>dp** in android) or the **tablet/phone** qualifiers you are pretty much on the safe side, as they will not change at runtime regardless the orientation. 

It seems to me that the best approach is to use different files when you want to define different application flow and/or layouts for tablet and phone(based on the minWH). From then on - use mq to make the best use of the available space or handle orientation changes. Also the [layout containers](http://docs.nativescript.org/layouts#predefined-layouts) in NS are quite powerful, so they can even save you from having to write complex media queries in most cases.

**Comment by sebawita** [comment]
I agree that there shouldn't be separate files for landscape and portraits. Especially if that would  mean reloading the whole page.

As for the Screen Size Qualifiers we should provide a list of them in a dictionary file like( I wouldn't use this specific format, but it should convey the message):
{
**small**: W(0,400) H(0,240)
**medium**: W(400, 600) H(240,320)
**medium-wide**: W(600, 800) H(240,320)
**large**: W(800, 1200) H(320, 600)
}
so that out of the box: homeView.ios.**medium**.js would be used when screen res would be the range of width 240-320 and height 400-600.

And if we provide this as a dictionary then this would be editable by devs who would like to create their own groups. For example you might want to have only 2 groups:
{
**phone**: W(0,320) H(0,600)
**tablet**: W(320, 600) H(600, 1200)
}

**Comment by ligaz** [comment]
I think the current proposal is a little bit overengineered. The main problem I have is that you will have to think hard what you number you need to specify in the `minWH<N>`. Having just `tablet` and `phone` qualifiers along with `land` and `port` should be more than enough to cover most of the cases. We can expand with more qualifiers in the future based on customer needs.

Also do we need to support the platform qualifier. As noted the CLI (and AppBuilder) already supports it so it will be very hard to end-up with `*.android.*` file on an actual device - the file should be named `*.android.android.*` in order for this to happen.

**Comment by FlipOne** [comment]
This will probably provide some ideas and help move things in the right direction --- Google has published a new reference app for multi-device applications. The reference app is on Github (https://github.com/googlesamples/android-UniversalMusicPlayer), and a brief announcement article on it (http://android-developers.blogspot.de/2015/03/a-new-reference-app-for-multi-device.html).

**Comment by vakrilov** [comment]
@ligaz Using `minWH<N>` is more flexible than just `tablet` or `phone`. Actually, android supports something similar(`small`, `normal`, `large` and `xlarge`), but they recommend using the [new size qualifiers](http://developer.android.com/guide/practices/screens_support.html#NewQualifiers) as they are more precise. 
Here is an example - you are implementing two pane layout and you need to be sure that you have 300 pixels for the side content and at least 400 for the main content, regardless the device orientation. So you define the layout in with `minWH700` qualifier. With a `tablet` modifier you will only have one option for the min width/height parameter at your disposal. 

About the platform qualifiers: you are right - they are already supported. I have included them for completeness.

**Comment by ligaz** [comment]
I completely agree that `minHW<N>` is more flexible there is no doubt about this. However I like the simplicity of `tablet` and `phone` qualifiers which is similar to how iOS handles this with `~ipad` suffixes. 

My point was that we can start with just `tablet` and `phone` and then expand our support with more qualifiers in the future. Right now we will start with `minHW<N>` and we will have to support if forever :smile:

**Comment by valentinstoychev** [comment]
@ligaz I agree with you, but even Apple has started to move away from this way of working because it is not a scalable solution. Now that they have more than just phone and tablet they are running into problems and are introducing per-DPI qualifiers. I like the initial proposal and I don't think it is over-engineered. It was actually proposed by our UX designer and the implementation is pretty simple on our side. This approach seems to be adopted by everyone - Android, Windows and as I said iOS are starting to move in the same direction. [see here](https://developer.apple.com/library/ios/recipes/xcode_help-IB_adaptive_sizes/chapters/AboutAdaptiveSizeDesign.html)

We should however see how to make it more "tooling-friendly", but this is another story.

**Comment by joshjordan** [comment]
I agree with @ligaz - I think that for the vast majority of use cases, the developer is really just going to be choosing between the device form factors. Going deeper than that gets us into maintaining many separate artifacts for similar-but-sightly-different devices, which is the entire concept that we're trying to combat with cross-platform app development.

I'd prefer to see just `phone` and `tablet` views as well, with some other mechanism (media queries were suggested) to handle the minor adjustments between resolutions within the form factor.

**Comment by valentinstoychev** [comment]
Thanks everyone for the input! This feature is now implemented - please see the [blog post](https://www.nativescript.org/blog/introducing-resolution---specific-views-for-nativescript) announcing how this feature was implemented.
