### ISSUE TITLE
Create common UI module that includes most commonly used UI views

### ISSUE THREAD

**Issue by hshristov** [NativeScript/cross-platform-modules#164]
The purpose of this is to collect most commonly used UI modules into one module, so that they are "required" more easily. For example:
```
import ui = require("ui"); 

var btn = new ui.Button();
var lbl = new ui.Label();
var stack = new ui.StackPanel();
stack.orientation = ui.Orientation.horizontal;
```

**Comment by hamorphis** [comment]
The current version of TypeScript does not offer an easy way to implement this. Will wait for next versions.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#68
