### ISSUE TITLE
Images on <TabEntry> buttons

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/cross-platform-modules#184]
Hi,

Can I add images on tab buttons? Currently, I can do this:
<TabEntry title=“Title">
but I don’t find any image possibility. Is there any?

Thanks,
Eduárd

**Comment by enchev** [comment]
Hi Eduárd,

Images in tab buttons are not available yet however we are working on this and most probably it will be part of our next release (May).

Thanks,
Vlad

**Comment by edimoldovan** [comment]
Hi Vlad,

Very nice, thanks. I will be keeping an eye on things then :)

Eduárd

**Comment by hamorphis** [comment]
There is a new member of the TabViewItem interface called iconSource. You can specify either a the file path or the resource id of the icon that you want the respective tab to show.
