### ISSUE TITLE
Get contacts from device

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/cross-platform-modules#195]
Hi everyone,

Is there any way of reaching the iOS contacts?

Thanks,
Eduárd

**Comment by enchev** [comment]
Hi Eduárd,

You can try this code:
http://stackoverflow.com/questions/19027118/fetch-contacts-in-ios-7

This API is available in NativeScript as well!

Thanks,
Vlad

**Comment by edimoldovan** [comment]
I will, thanks.
Also, I am curious if this would be a possible approach for some more special future features, like this one. Do you plan to leave handle it like this, or have a higher level platform independent version of the feature in Nativescript?

**Comment by enchev** [comment]
We will have for sure - the community will add it even if we don't have it! :) @tjvantoll already added flashlight module: https://github.com/tjvantoll/nativescript-flashlight

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#65
