### ISSUE TITLE
Navigate to page toolbar/back button

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/cross-platform-modules#200]
Hi,

When navigating to a page there will be a default toolbar at the top with a back button in it (tried it on iOS only for now). Can that be removed in any way? There are cases when that is not necessarily needed.

Thanks,
Eduárd

**Comment by hamorphis** [comment]
You can try the following. Attach to the pageLoaded event of the page and do this in the event handler:

XML:
-------------------------------------------
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <StackLayout>
    <Label text="Page"/>
  </StackLayout>
</Page>

TypeScript:
-------------------------------------------
import pages = require("ui/page");
import observable = require("data/observable");

export function pageLoaded(args: observable.EventData) {
    var page = <pages.Page>args.object;

    if (page.ios) {
        (<UIViewController>page.ios).navigationItem.hidesBackButton = true;
    }
    else {
        // You cannot hide the back button in Andorid. There is not way.
    }
}

JavaScript:
-------------------------------------------
function pageLoaded(args) {
    var page = args.object;
    if (page.ios) {
        page.ios.navigationItem.hidesBackButton = true;
    }
    else {
    }
}
exports.pageLoaded = pageLoaded;

I have tried this and it did hide the back button in iOS.
