### ISSUE TITLE
Issues with the camera module

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/cross-platform-modules#201]
I gave the camera module a try today and ran into a few issues. Here's the code I'm using:

```
var camera = require("camera");
camera.takePicture().then(function(result) {
	console.log(JSON.stringify(result));
});
```

On iOS this code runs, and I'm able to take a picture, but the callback's `result` argument is set to `{"ios":{}}` on my iPhone 6+. On Android I'm having difficulty getting at the logs at the moment, but nothing appears to be returned on that platform either. Also, chaining a `fail()` call as [this module's README](https://github.com/NativeScript/cross-platform-modules/blob/master/camera/Readme.md) gives me a JS error.

I updated my project to the latest version of this repo and I'm still having problems. Any help would be appreciated.

Thanks.

**Comment by hamorphis** [comment]
I will take a look at this.

**Comment by hamorphis** [comment]
The takePicture method returns a promise of type imageSource.ImageSource. The result variable if of type imageSource.ImageSource: https://github.com/NativeScript/docs/tree/master/ApiReference/image-source

Here is what I did in TypeScript:

        camera.takePicture().then(
            function onFulfilled(value: imageSource.ImageSource) { 
                console.log(value.width + "x" + value.height);
            }, 
            function onRejected(error: any) {
                console.log(error);
            });

This translates to the following JavaScript:

        camera.takePicture().then(function onFulfilled(value) {
            console.log(value.width + "x" + value.height);
        }, function onRejected(error) {
            console.log(error);
        });

I tested it on Android and iOS and I got the picture dimensions logged out. Look at the ImageSource API ref to see what methods and properties it has. You can save the image to disk, you can show it in your app, etc.

**Comment by tjvantoll** [comment]
Huh. I tried this code today and it works now. I'm not sure if I had something cached or what.

I will say that chaining a `fail()` call as [this module's README](https://github.com/NativeScript/cross-platform-modules/tree/master/camera) shows still gives me a JavaScript error.

Also it'd be great if the camera module's HOW-TO.md had a simple example of how to show the image on the screen. I'm trying to get that to work right now and having issues.

Thanks so much for your help on this.

TJ

**Comment by hamorphis** [comment]
I assume that the help has not been updated yet. To show the image on the screen, you should use the Image widget: https://github.com/NativeScript/docs/blob/master/ApiReference/ui/image/HOW-TO.md

The onFulfilled callback will give you an imageSource variable. Then assign this imageSource variable as the imageSource of the image widget and it will display it, i.e.

camera.takePicture().then(function onFulfilled(value) {
        myImage.imageSource = value;
    }, function onRejected(error) {
        console.log(error);
    });
