### ISSUE TITLE
Allow to create Observable instance from javascript (json) objects

### ISSUE THREAD

**Issue by kvelikov** [NativeScript/cross-platform-modules#210]
For example in the constructor: new Observable({ name: "John Doe" });

**Comment by hamorphis** [comment]
Here is how you can do this.

    var json = {
        Name: "John",
        Age: 34,
        Married: true
    };
    var person = new observable.Observable(json);

**Comment by paveldk** [comment]
#215

**Comment by hamorphis** [comment]
I have seen the pull request. Can you provide a practical example of what it achieves and is not possible with a TypeScript extends. Thanks.
