### ISSUE TITLE
Tap is not triggered on Label when subscribed in XML

### ISSUE THREAD

**Issue by estoychev** [NativeScript/cross-platform-modules#219]
<Label text="Login" tap="{{ onLoginTap }}" />

Tap is not triggered.

It works fine when I subscribe from code.

**Comment by enchev** [comment]
Just tested with the latest modules from master branch and everything worked as expected. You can check for example [this implementation][(https://github.com/NativeScript/cross-platform-modules/blob/master/apps/TelerikNEXT/main-page.xml#L60)] and change the Image to Label to test it.
