### ISSUE TITLE
Implement NativeView placeholder

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/cross-platform-modules#230]
Currently we have our abstract Visual Tree (DOM) implementation and the layout logic is applied only to nodes, part of the tree. If the user wants to insert a native widget directly, it will not be part of our abstraction and no layout/events/lifecycle will be applied to it.

What we may do is to implement a generic placeholder, which will simply wrap any arbitrary native widget, making it part of the abstract visual tree.

See [this conversation](https://groups.google.com/forum/#!topic/nativescript/jMRmLaF1JyU) for more information.

**Comment by hamorphis** [comment]
https://github.com/NativeScript/docs/blob/master/placeholder.md
