### ISSUE TITLE
Rotating the device makes ListView desappear (iOS)

### ISSUE THREAD

**Issue by ligaz** [NativeScript/cross-platform-modules#233]
_From @jgamedev on March 26, 2015 23:33_

While completing the in-browser AppBuilder tutorial and testing in both platforms, I noticed that in iOS the list  - or its contents -   desappears quite frequently when you rotate the device.

If you try to scroll, the list re-appears.

Tested on Ipod 5 running iOS 7.0.4

_Copied from original issue: NativeScript/NativeScript#23_

**Comment by jgamedev** [comment]
That's refering to the interactive photo album tutorial ( NativeScript version) , just to be clear.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#61
