### ISSUE TITLE
iOS - Swipe Backwards Navigation - Half Swipe

### ISSUE THREAD

**Issue by ligaz** [NativeScript/cross-platform-modules#234]
_From @papaytl185 on March 24, 2015 13:47_

If you begin to swipe backward in ios to go to the previous page, but then stay on the current page it will lock / freeze the app. This happens for all the sample applications as well. I am using appbuilder companion app, iphone 6 - ios 8.2

_Copied from original issue: NativeScript/NativeScript#20_

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#60
