### ISSUE TITLE
Button tap event doesn't fire if inline style is set

### ISSUE THREAD

**Issue by brianchirls** [NativeScript/cross-platform-modules#239]
This works:

```xml
<Button text="PLAY" tap="{{ play }}" />
```

This does not (nothing happens):
```xml
<Button text="PLAY" tap="{{ play }}" style="font-size: 40" />
```

The device-native onClick handler is firing just fine, but there are no events registered. So I'm guessing it's a parsing problem. Same effect on both Android and iOS.

**Comment by enchev** [comment]
This issue is already fixed in our master branch!

**Comment by brianchirls** [comment]
Couldn't find an issue for it, but great! Thanks.

**Comment by enchev** [comment]
Sorry! Here is the pull request: https://github.com/NativeScript/cross-platform-modules/pull/140
