### ISSUE TITLE
Stop calling metadata generator and build twice for android platform.

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/cross-platform-modules#241]
_From @teobugslayer on April 1, 2015 15:0_

Instead, the project template will supply a custom ants hook to do the work

Also, cache the platformData
Also, starting ant through the user command interpreter falling back to cmd

See https://github.com/NativeScript/android-runtime/issues/47

_Copied from original issue: NativeScript/nativescript-cli/pull/405_

**Comment by teobugslayer** [comment]
_From @ns-bot on April 1, 2015 15:1_

:white_check_mark:

**Comment by teobugslayer** [comment]
ping @plamen5kov, @atanasovg

**Comment by teobugslayer** [comment]
_From @rosen-vladimirov on April 1, 2015 15:5_

:+1:  awesomeeeeeee

**Comment by teobugslayer** [comment]
_From @ns-bot on April 1, 2015 15:10_

:white_check_mark:

**Comment by teobugslayer** [comment]
_From @ns-bot on April 1, 2015 15:18_

:white_check_mark:

**Comment by teobugslayer** [comment]
_From @Plamen5kov on April 1, 2015 15:18_

:+1:

**Comment by teobugslayer** [comment]
**Do not merge before the new project templates!**

**Comment by teobugslayer** [comment]
_From @ns-bot on April 1, 2015 15:22_

:white_check_mark:

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#58
