### ISSUE TITLE
Camera: Memory issues on iOS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/cross-platform-modules#257]
Hey all,

I'm having an issue with the camera module on iOS. [My code](https://github.com/NativeScript/conf-next-2015-workshop/blob/3102c093a7ba68f98bed540396892fa80ed68e07/app/app/components/edit-meme/edit-meme.js#L16-20) is pretty simple; @hamorphis [helped me out with it](https://github.com/NativeScript/cross-platform-modules/issues/201).

```js
camera.takePicture().then(function(r) {
    data.set("imageSource", r);
}, function(e) {
    alert("An error occurred taking the photo");
});
```

On Android this code runs fine. On iOS this code occasionally works, but it usually just crashes my app. Here's [a full crash log](https://gist.github.com/tjvantoll/e0636dcfb973286a901f). I'm no expert at reading these logs, but the issue appears to be related to memory:

```
[0;37mApr  3 11:29:58 iPhone[0;36m UserEventAgent[20][2;33m <[0;33mWarning[2;33m>[0;37m:[m low memory session log
[0;37mApr  3 11:29:59 iPhone[0;36m InCallService[452][2;33m <[0;33mWarning[2;33m>[0;37m:[m Received memory warning.
[0;37mApr  3 11:29:59 iPhone[0;36m MobileSMS[730][2;33m <[0;33mWarning[2;33m>[0;37m:[m Received memory warning.
[0;37mApr  3 11:29:59 iPhone[0;36m discoveryd[55][2;32m <[0;32mNotice[2;32m>[0;37m:[m Basic DeviceInformation Memory Pressure Warning sent: pressure
[0;37mApr  3 11:29:59 iPhone[0;36m locationd[1624][2;32m <[0;32mNotice[2;32m>[0;37m:[m Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
[0;37mApr  3 11:29:59 iPhone[0;36m locationd[1624][2;32m <[0;32mNotice[2;32m>[0;37m:[m Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
[0;37mApr  3 11:29:59 iPhone[0;36m locationd[1624][2;32m <[0;32mNotice[2;32m>[0;37m:[m Gesture EnabledForTopCLient: 0, EnabledInDaemonSettings: 0
[0;37mApr  3 11:29:59 iPhone[0;36m wifid[37][2;31m <[0;31mError[2;31m>[0;37m:[m WiFi:[449767799.143421]: kern_return_t _wifi_manager_open(mach_port_t, int, int, mach_port_t, mach_port_t *, audit_token_t) Client WirelessRadioMan has no entitlement
[0;37mApr  3 11:29:59 iPhone[0;36m SpringBoard[53][2;33m <[0;33mWarning[2;33m>[0;37m:[m Application 'UIKitApplication:com.apple.mobilemail[0xea61]' was killed by jetsam.
```

I'm running an iPhone 6 Plus, so I'm guessing the pictures I'm taking take up a lot of memory, which might be contributing to the problem.

Anyways any help would be appreciated. I'm not sure whether I'm on the right track with memory usage or not. I'm going to start looking into how the Cordova camera plugin's `quality` property works to see if I can come up with a workaround (assuming this actually is a memory problem).

Thanks!

**Comment by tjvantoll** [comment]
I was able to work around this by adding some resizing logic in `UIImagePickerControllerDelegateImpl.prototype.imagePickerControllerDidFinishPickingMediaWithInfo`:

```js
var source = info.valueForKey(UIImagePickerControllerOriginalImage);
var newSize = CGSizeMake(750, 450); // hardcode 750x450
UIGraphicsBeginImageContext(newSize);
source.drawInRect(
    CGRectMake(0, 0, newSize.width, newSize.height)
);
```

So I think the answer here might just be adding `height` and `width` options.

**Comment by nsndeck** [comment]
Added custom size for camera pictures with commit #283.
