### ISSUE TITLE
Camera: Tiny images on Android

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/cross-platform-modules#258]
The camera module's `takePicture()` method seems to be returning a thumbnail rather than the full image. On my Nexus 4 using the code below I get an image that's 153 x 204:

```js
camera.takePicture().then(function(r) {
    alert( "Height: " + r.android.getHeight() + ", Width: " + r.android.getWidth() );
    data.set("imageSource", r);
}, function(e) {
    alert("An error occurred taking the photo");
});
```

This seems to be a fairly common problem: http://stackoverflow.com/questions/6448856/android-camera-intent-how-to-get-full-sized-photo

**Comment by nsndeck** [comment]
Solved with commit #283.
