### ISSUE TITLE
topmost().navigate always creates a header bar

### ISSUE THREAD

**Issue by ligaz** [NativeScript/cross-platform-modules#259]
_From @rubenstolk on March 16, 2015 9:49_

We need a way to change the `mainModule`, for example initially your `mainModule` is the login screen, but once the user is logged in you want the home screen to be the `mainModule`.

I haven't figured out a way to be able to do this...

_Copied from original issue: NativeScript/NativeScript#16_

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#55
