### ISSUE TITLE
API Notifications

### ISSUE THREAD

**Issue by ligaz** [NativeScript/cross-platform-modules#260]
_From @unlight on January 20, 2015 15:55_

Not sure, that is right place for issue.
But I found nothing about notifications [ApiReference][1].
Will it be available in future version of NativeScript?

[1]: https://github.com/NativeScript/docs/tree/master/ApiReference

_Copied from original issue: NativeScript/nativescript-cli#192_

**Comment by ligaz** [comment]
Hi unlight,

Can you please elaborate what kind of Notification API you are expecting? I guess you are talking about Push Notifications and Local Notifications.

**Comment by ligaz** [comment]
_From @unlight on March 6, 2015 15:50_

I mean something like this
![example](http://www.vogella.com/tutorials/AndroidNotifications/images/xnotification10.png.pagespeed.ic.fmc6zyoaDS.png)
http://www.vogella.com/tutorials/AndroidNotifications/article.html

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#54
