### ISSUE TITLE
Wrong tab highlighted (TabView - Android)

### ISSUE THREAD

**Issue by ritcoder** [NativeScript/cross-platform-modules#261]
![screenshot_2015-04-05-00-07-06](https://cloud.githubusercontent.com/assets/254737/6995181/f37b90bc-db27-11e4-93af-76bc3b0f7b0f.png)
I created a simple tab-view app with 2 tabs. I realized that irrespective of the selected tab, when I move out of the application and come back (lock and unlock the phone), the right tab view (page) is shown but the first tab is always selected.

The sample view used is
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="onPageLoaded">
  <TabView>
    <TabView.items>
      <TabViewItem title="Tab 1">
        <TabEntry.view>
          <Label text="This is tab 1"/>
        </TabEntry.view>
      </TabViewItem>
      <TabViewItem title="Tab 2">
        <TabEntry.view>
          <Label text="This is tab 2"/>
        </TabEntry.view>
      </TabViewItem>
    </TabView.items>
  </TabView>
</Page>

**Comment by ritcoder** [comment]
Looks like the xml for the sample view did not appear. It was however a very simple view with two tabs. Also, I'm using Nexus 5 and have updated to the latest NSM files. Was the same issue before I updated.

**Comment by hamorphis** [comment]
I will take a look at this.

**Comment by hamorphis** [comment]
I have been able to reproduce this and I will start working on a fix.

**Comment by hamorphis** [comment]
Here is a [link](https://www.dropbox.com/s/z3emzee88475jok/Issue261.zip?dl=0) to a sample app I built with the fixed version of our sources.

**Comment by ritcoder** [comment]
I'm unable to build this.

```
BUILD FAILED
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:653: The following error occurred while executing this line:
C:\Program Files (x86)\Android\android-sdk\tools\ant\build.xml:698: null returned: 1

Total time: 0 seconds
```

I did pull the latest build from git and it is now working correctly. Thanks.
Should I close this ticket?

**Comment by hamorphis** [comment]
This version in the master branch is not compatible with the current release of the Command Line Interface. If you wait for a couple of days we will have an official release where everything should work out of the box.
