### ISSUE TITLE
Back button handling

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/cross-platform-modules#266]
Hi guys,

Is it just me or there is no way currently to handle the hardware back button click for Android devices? I need some custom logic since I show/hide stacklayouts dynamically on the same page.

**Comment by nsndeck** [comment]
It is not recommended to alter the hardware navigation (Android). For such cases you can add a dedicated button on top-left corner of the application as shown in [this](http://developer.android.com/design/patterns/navigation.html) UX guideline.

**Comment by MiroValchev** [comment]
Ok, thanks for the comment. Coming from Windows Phone background :)
