### ISSUE TITLE
Button tap action not firing under GridLayout

### ISSUE THREAD

**Issue by ligaz** [NativeScript/cross-platform-modules#269]
_From @damjankuznar on April 7, 2015 12:20_

I'm trying to setup a simple UI using the GridLayout and I came across something odd (the whole project is based on HelloWorld example).  In some setups the Button is not firing the tap action.
For instance, the following setup is working correctly, i.e. the tapAction function is called.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="1"/>
    <Button text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

However, if I add the `row="0"` attribute to the Button, the tapAction function is not being called. Same goes for setting any other row value.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="1"/>
    <Button text="TAP" tap="{{ tapAction }}" row="0"/>
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

Is this a bug or am I doing something wrong?

_Copied from original issue: NativeScript/NativeScript#36_

**Comment by ligaz** [comment]
_From @damjankuznar on April 7, 2015 12:44_

I've been playing around some more and the tap action works if the `row` attribute is the first one defined in the Button element, i.e.
```
<Page xmlns="http://www.nativescript.org/tns.xsd" loaded="pageLoaded">
  <GridLayout rows="auto, auto, *" columns="*">
    <Label text="Tap the button" cssClass="title" row="0"/>
    <Button row="1" text="TAP" tap="{{ tapAction }}" />
    <Label text="{{ message }}" cssClass="message" textWrap="true" row="2"/>
  </GridLayout>
</Page>
```

**Comment by ahalls** [comment]
I'm finding that if you put a button in the first element,  row=0, col=0  in iOS there is a ghost view placed over the button.  Which prevents the button from being tapped.  If I put in thin, one pixel row the ghost view does not block a button.   Seems that this would work with the above example where @ligaz moves the button down to the second row and it works.

```
    <GridLayout rows="1,54,54" columns="120, 120"
        horizontalAlignment='center' >
        <Button class='welcome-button'
            row="1" col="0" 
            text="Visit"
            tag="plan"
            (tap)='onButtonTap($event)' > 
         </Button>
        <Button class='welcome-button'
            row="1" col="1" 
            text="Explore"
            tag="ground"
            (tap)='onButtonTap($event)' > 
        </Button>
        <Button class='welcome-button'
            row="2" col="0" 
            text="Connect"
            tag="connect"
            (tap)='onButtonTap($event)' > 
        </Button>
        <Button class='welcome-button'
            row="2" col="1" 
            text="Give"
            tag="give"
            (tap)='onButtonTap($event)' > 
        </Button>
    <GridLayout>
```
