### ISSUE TITLE
image-cache doesn't work for URL based images with no suffix

### ISSUE THREAD

**Issue by mollyfud** [NativeScript/cross-platform-modules#270]
If you try and add a URL based image to an image-cache, if the url doesn't have a file suffix of either .png or .jpg the process won't work. To what I could see (after trying to get this working for a while), no error or message is logged on this either.
And example of  a URL that fails is:
http://lh5.ggpht.com/wjZeO3l-lPRUtZXopQVJ9HGjNi4sVBrsf27dfWMJb60yQnXMONAwOBZqL-3o54ovLUEw_6mlgz1IRj5-6DvFhsTynYzBeNLwYOlzgx4wEFLmL7jh

**Comment by hamorphis** [comment]
I fixed this. Unfortunately, it will not make it for the 0.10.0 release since we are in a code freeze. But you can always pull the latest sources from GitHub.
