### ISSUE TITLE
Proper way to retrieve location with Android

### ISSUE THREAD

**Issue by edimoldovan** [NativeScript/cross-platform-modules#274]
I have been trying to implement a simple location retrieval for both iOS and Android. The iOS part seams to be fine. Android on the other hand seams to not be OK, though I am not getting any errors.

First, I added this `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>` to the `AndroidManifest.xml`, the tried to retrieve location like this:
```
    if (platform.device.os === "iOS") {
		locationManager.iosLocationManager.requestWhenInUseAuthorization();
	} else if (platform.device.os === "Android") {
		/*dialogs.confirm("Location service is not enabled!", {
      okButtonText: "Open location settings ...",
      cancelButtonText: "Cancel", title: "Confirm"
    }).then(function(r) {
      if (r) {
				appModule.android.currentContext.startActivityForResult(new android.content.Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS), 0);
      }
    }, null);*/
	}

	location.getLocation({
		maximumAge: 30000,
		timeout: 5000 })
	.then(function (location) {
          var options = {
			title: "DEBUG",
			message: "Received location",
			okButtonText: "OK"
		};
		dialogs.alert(options).then(function () {});
        }, function (error) {
		console.log("Location error received: " + error);
	});
```

I have the commented out part because it somehow made think that it is doing nothing over there due to when tapping the OK I get to a screen saying that the app has already requested location lately. 

I am not sure why I am not getting the data, perhaps enabling GPS in Genimotion emulator is not enough for location to be determined (in iOS we need to provide the mocked location in the emulator menu under Debug->Location).

Any ideas?

**Comment by edimoldovan** [comment]
I have some updates: it looks like location is throwing some error, just haven’t been able to get the description of the error so far. Will post when I do that.

**Comment by nsndeck** [comment]
Unfortunately there is no way to test location with an Android emulator, due to limitation of the platform. For all location specific features you should use a real device.

**Comment by edimoldovan** [comment]
I didn’t know that, thanks for pointing it out.
