### ISSUE TITLE
Improve the console module

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/cross-platform-modules#281]
The current console implementation uses the built-in `console` object for iOS and our custom JavaScript implementation for Android. This custom implementation is not behaving like the Web one and works for primitive types only (and plain Objects, without circular references). We may take a look at how [Node.js](https://github.com/joyent/node/blob/master/lib/console.js) have implemented it.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#49
