### ISSUE TITLE
Set Platform Specific Properties In XML

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/cross-platform-modules#288]
Currently the JavaScript classes frequently have **ios** and **android** properties that control platform specific behavior. I would like to set them in XML

### Either Using XML Namespaces
Platform specific attribute:
```XML
<Page
    xmlns="http://www.nativescript.org/tns.xsd"
    xmlns:ios="platform:ios">
    ios:title="General">
</Page>
```
Platform specific element:
```XML
<Page
    xmlns="http://www.nativescript.org/tns.xsd"
    xmlns:ios="platform:ios">
    <ios:Page.title>General</ios:Page.title>
</Page>
```

### Or Using Dot Syntax
Platform specific attribute:
```XML
<Page
    xmlns="http://www.nativescript.org/tns.xsd"
    ios.title="General">
</Page>
```
Platform specific element:
```XML
<Page xmlns="http://www.nativescript.org/tns.xsd">
    <Page.ios.title>General</Page.ios.title>
</Page>
```

**Comment by enchev** [comment]
Finally dot syntax was implemented!
