### ISSUE TITLE
Circle element using border

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/cross-platform-modules#313]
I wanted to show user's avatar in circle. To do this I tried using image nested in border.
1. I succeeded creating the circle, but the nested image was showing outside the boundaries of the border. Is this the desired behavior for border?
2. If you don't set a color for border, an exception is thrown. In the above example I want to use the border just for the rounded shape so a transparent default color sounds legit?

**Comment by enchev** [comment]
Hey @MiroValchev! Can you post the code of your border and the exception related to color? Generally our Border class do no have any color by default.

**Comment by MiroValchev** [comment]
This works just, except that it does not cut the image in a circle as expected.
<Border cssClass="user-picture" cornerRadius="100" borderColor="grey" borderWidth="3">
                  <Image cssClass="user-picture" src="{{ PictureUrl }}" stretch="aspectFill" />
</Border>

This one throws exception. I have just removed the borderColor. 
<Border cssClass="user-picture" cornerRadius="100" borderWidth="3">
                  <Image cssClass="user-picture" src="{{ PictureUrl }}" stretch="aspectFill" />
</Border>


[JS      ] Application error: Error; The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception.; com.tns.NativeScriptException: 
[JS      ] Calling js method onCreateView failed
[JS      ] 
[JS      ] TypeError: Cannot read property 'android' of undefined
[JS      ] File: "ui/border, line: 18, column: 55
[JS      ] 
[JS      ] StackTrace: 
[JS      ] 	Frame: function:'onCornerRadiusPropertyChanged', file:'ui/border', line: 18, column: 56
[JS      ] 	Frame: function:'ProxyObject._trySetNativeValue', file:'ui/core/proxy', line: 86, column: 27
[JS      ] 	Frame: function:'eachPropertyCallback', file:'ui/core/proxy', line: 65, column: 18
[JS      ] 	Frame: function:'DependencyObservable._eachSetProperty', file:'ui/core/dependency-observable', line: 359, column: 22
[JS      ] 	Frame: function:'ProxyObject._syncNativeProperties', file:'ui/core/proxy', line: 68, column: 14
[JS      ] 	Frame: function:'View._syncNativeProperties', file:'ui/core/view-common', line: 770, column: 48
[JS      ] 	Frame: function:'View._onContextChanged', file:'ui/core/view', line: 140, column: 14
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 95, column: 14
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'TabView._eachChildView', file:'ui/tab-view/tab-view-common', line: 151, column: 26
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'TabView._onAttached', file:'ui/tab-view', line: 196, column: 38
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'Layout._eachChildView', file:'ui/layouts/layout', line: 50, column: 22
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'eachChild', file:'ui/core/view', line: 100, column: 23
[JS      ] 	Frame: function:'ContentView._eachChildView', file:'ui/content-view', line: 51, column: 13
[JS      ] 	Frame: function:'View._onAttached', file:'ui/core/view', line: 106, column: 18
[JS      ] 	Frame: function:'View._addViewCore', file:'ui/core/view', line: 75, column: 18
[JS      ] 	Frame: function:'View._addView', file:'ui/core/view-common', line: 705, column: 14
[JS      ] 	Frame: function:'onFragmentShown', file:'ui/frame', line: 153, column: 11
[JS      ] 	Frame: function:'PageFragmentBody.onCreateView', file:'ui/frame', line: 46, column: 13
[JS      ]

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#44
