### ISSUE TITLE
app.platform.css should compliment app.css and not replace it

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/cross-platform-modules#314]
From my tests, if platform specific versions of app.css are added, the original file is completely ignored. Shouldn't they just compliment it by overriding some styles?

**Comment by sfeather** [comment]
Agreed, @MiroValchev . The two should be merged with platform specific styles being added to (and overwriting conflicting) app level styles.  This merging needs to take place at the property level.

**Comment by enchev** [comment]
Hey folks,

You are right. Currently our CLI will remove "platform" part from the file name and will replace app.css if any. We plan to support [CSS import](https://developer.mozilla.org/en/docs/Web/CSS/@import) for common and platform specific declarations.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#43
