### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by khadorkin** [NativeScript/cross-platform-modules#315]
Hello!
Can you clarify, how i can use localization for application?

Thank you!

**Comment by enchev** [comment]
The easiest way will be create a view-model with desired properties, get localized properties values from resources:
http://developer.android.com/guide/topics/resources/localization.html
http://www.raywenderlich.com/64401/internationalization-tutorial-for-ios-2014
and [bind your UI components](http://docs.nativescript.org/ui-with-xml#property-binding) to the view-model properties.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#42
