### ISSUE TITLE
Transparency in Modal Page.

### ISSUE THREAD

**Issue by aylesm** [NativeScript/cross-platform-modules#320]
Hi,

I'm trying to set a modal page to be transparent so I can see the underlying page on iOS.  I've tried setting the css background-color to 'transparent'.  I've also tried setting it using hex following another issue raised here like this: #88FF0000.  Neither works for me.  My page is very simple...

`<Page loaded="loaded" xmlns="http://schemas.nativescript.org/tns.xsd">`
`  <StackLayout orientation="vertical">`
`    <Label text="some title" class="title"/>`
    `    <Label text="some content" textWrap="true"/>`
`    <Button text="Ok" tap="dismiss" />`
`  </StackLayout>`
`</Page>`

Any help would be appreciated.

Thanks.

**Comment by mobilemindtec** [comment]
Hi, did you find a solution?

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/NativeScript#2086
