### ISSUE TITLE
Research Font Awesome support

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/cross-platform-modules#33]
Research if it is possible to have a Font-Awesome module. Check [the respective forum thread](http://www.telerik.com/forums/font-awesome) for more information as well as `ios` and `android` samples!

**Comment by edimoldovan** [comment]
There are also these which look interesting:
iOS: https://github.com/alexdrone/ios-fontawesome
Android: https://github.com/JoanZapata/android-iconify

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#78
