### ISSUE TITLE
Detailed rounded corners

### ISSUE THREAD

**Issue by ErjanGavalji** [NativeScript/cross-platform-modules#36]
Implement detailed corner radius specification. See [the respective forum post](http://www.telerik.com/forums/styling-labels-with-borders) for a detailed request.

The following [ios](http://stackoverflow.com/questions/10167266/how-to-set-cornerradius-for-only-top-left-and-top-right-corner-of-a-uiview) and [android](http://stackoverflow.com/questions/6054562/how-to-make-the-corners-of-a-button-round) hints might help with the implementation.

**Comment by enchev** [comment]
This issue was moved to NativeScript/NativeScript#77
